Skaphandrus\OceanlifeidBundle\Entity\Contact:
    type: entity
    table: contact
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 70
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 70
            fixed: false
            comment: ''
        message:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
